### PR TITLE
Added my Project -SirCashier

### PR DESCRIPTION
**Pull request by AlfatTaufik**
I hope youre liked my project, tell me if i had to make a change
I will lovely to do that

### CODE REVIEW

**Review by hackelite01 — CHANGES_REQUESTED** [review]
What a big brain!!! Its mind blowing. Just a suggestion: add how to use the code in the README file so community can also use it.

**Comment by AlfatTaufik** [comment]
Allright sir, working on it

**Comment by AlfatTaufik** [comment]
There u go sir

**Review by hackelite01 — APPROVED** [review]
Perfect

**Comment by AlfatTaufik** [comment]
Thanks sir!!!

**Pull request merged**
