### PR TITLE
Add NewsPulse React app with API integration for real-time news updates

### PR DESCRIPTION
**Pull request by syedmaazsaeed**
@hackelite01 

NewsPulse is a dynamic React-based news application that I’ve built, powered by the News API. It delivers real-time news updates across various categories such as general, business, entertainment, health, science, sports, and technology. The app features:

Endless scrolling for quick loading of articles
Responsive design for seamless experience on all platforms
Progress indicators for API requests
Multiple categories for browsing, including technology, business, health, and more

Here is my Issue Number : NewsPulse App - Real-time News Platform using React #23

Submit a pull request for your review.

### CODE REVIEW

**Comment by syedmaazsaeed** [comment]
@hackelite01 

I have contributed to the project through a pull request. Please check it out.

Issue Number : Add NewsPulse React app with API integration for real-time news updates  { #28 }

**Comment by syedmaazsaeed** [comment]
@hackelite01

I have contributed to the project through a pull request. Please review it and merge it into the main branch so that it can count towards Hacktoberfest 2024.

 Currently, the repository is showing as "excluded" on my Hacktoberfest page.

 Could you please let me know why this might be happening?

Screenshot 2024-10-07 231858

**Review by hackelite01 — APPROVED** [review]
Perfect

**Comment by hackelite01** [comment]
fixes #23

**Pull request merged**
